### ISSUE TITLE
Error for retrieving OKCoin pricing

### ISSUE THREAD

**Issue by accnops** [jxm262/btc-stats#4]
At the moment, OKCoin does not return a JSON response. This results in an error when evaluating JSON.parse(...) in xchange.js.

This issue can be resolved by:

- In xchange.js: Wrapping JSON.parse(...) with a try catch (or alternative fix).
- In btc-stats: Don't let errors cascade. When calculating weightedAvg for example, ignore the exchanges that returned an error.

As this fix must be applied to two repos, I was hoping @jxm262 could fix this. Is this possible?

Thanks in advance!

**Comment by jxm262** [comment]
@accnops  thanks for reporting.  I'm actually about to release version 1.0 of xchange.js here soon, which will have alot more functionality and a few more exchanges.  I'll take a look at this issue on btc-stats right after I release the next version of xchange.js (hopefully a day or so)

**Comment by accnops** [comment]
Thanks a lot! Will btc-stats use the new version of xchange.js?

What do you think about filtering out exchanges that return errors?
Every exchange has downtimes. To place your trust in the uptime of the exchanges would't be smart I think. In this way the library would become more robust.

**Comment by jxm262** [comment]
yeah, btc-stats will most likely use the new version of xchange.js.  I think you have a valid point, so long as the errors aren't swallowed somewhere and the user knows can easily find out what wasn't valid.  Perhaps we could make the response be something like - 
```
btcstats.weightedAvg(function(error, resp) {
    //response format { price: xxx, errors: [exchange: 'okcoin', msg: 'unable to reach service'] }
});
```

or something along those lines

**Comment by jxm262** [comment]
@accnops Side note if you're interested, the docs for version 1  are here - 
https://jxm262.github.io/xchange.js/

its' not fully complete but if you check back in a few days the full code will be pushed up on npm with a fully clean version of the docs.   Just need to wrap up a couple small issues, couple more docs, and do some more tests.  Almost ready though!
